checks:
    php: true
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=./build/logs/clover'
                coverage:
                    file: './build/logs/clover'
                    format: 'xml'
tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
        runs: 2         # Scrutinizer will wait for two code coverage submissions