dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - composer self-update
    - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT