dist: trusty
sudo: false
language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
    - composer self-update
    - composer clear-cache
    - composer install --dev --prefer-source --no-interaction
    - composer update codacy/coverage --dev

script:
  - bundle exec rspec
  - vendor/bin/phpunit

after_script:
  - if [ -f vendor/bin/codacycoverage ] ; then php vendor/bin/codacycoverage clover || true ; fi
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT